name: terruar-gallery
networks:
  terruar:

x-default-env: &default-env
  DEV: ${DEV}
  API_PATH: ${API_PATH:?}
  API_PATH_LOCAL: ${API_PATH_LOCAL:?}
  DIR_PUBLIC: /app/${DIR_PUBLIC:?}
  API_KEY: ${API_KEY:?}
  REDIS_URL: ${REDIS_URL:-redis://redis:6379}

services:
  app:
    build:
      context: .
      args: *default-env

    restart: 'unless-stopped'
    expose:
      - 3000

    environment: *default-env

    healthcheck:
      test:
        [
          'CMD-SHELL',
          'bun -e "fetch(''http://localhost:3000/gallery'')" || exit 1',
        ]
      interval: 5m
      timeout: 30s
      retries: 3
      start_period: 30s

    depends_on:
      redis:
        condition: service_healthy

    networks:
      - terruar

  redis:
    container_name: terruar-gallery-redis
    image: redis:8-alpine
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: 200M
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - terruar
